/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jinjuamla.esp8266.imageflasher;

import javax.swing.DefaultListModel;

/**
 *
 * @author psammand
 */
public class BootLoaderSelectionDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;
    private int _dialogResult = 0;

    public BootLoaderSelectionDialog() {
        initComponents();
        
    }

    public BootloaderSelectionModel getBootloaderSelectionModel() {
        return bootloaderSelectionModel;
    }

    public void setBootloaderSelectionModel( BootloaderSelectionModel bootloaderSelectionModel ) {
        this.bootloaderSelectionModel = bootloaderSelectionModel;
    }

    public void setListModel( DefaultListModel<String> model ) {
        _booltloaderList.setModel( model );
    }

    public int getResult() {
        return _dialogResult;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        bootloaderSelectionModel = new BootloaderSelectionModel();
        _closeBut = new javax.swing.JButton();
        _okBut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _booltloaderList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        _customBootloaderTxt = new javax.swing.JTextField();
        _customBootloaderBrowseBut = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bootloader Selection");

        _closeBut.setText("Close");
        _closeBut.addActionListener(formListener);

        _okBut.setText("Ok");
        _okBut.addActionListener(formListener);

        jLabel1.setText("Available bootloaders");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bootloaderSelectionModel, org.jdesktop.beansbinding.ELProperty.create("${bootloaderFileName}"), _booltloaderList, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(_booltloaderList);

        jLabel2.setText("Custom bootloader :");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bootloaderSelectionModel, org.jdesktop.beansbinding.ELProperty.create("${customBootloader}"), _customBootloaderTxt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        _customBootloaderBrowseBut.setText("Browse");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_customBootloaderTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_customBootloaderBrowseBut)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(_customBootloaderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_customBootloaderBrowseBut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(521, Short.MAX_VALUE)
                .addComponent(_okBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_closeBut)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_closeBut)
                    .addComponent(_okBut))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == _okBut) {
                BootLoaderSelectionDialog.this._okButActionPerformed(evt);
            }
            else if (evt.getSource() == _closeBut) {
                BootLoaderSelectionDialog.this._closeButActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void _okButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__okButActionPerformed
        _dialogResult = 1;
        dispose();
    }//GEN-LAST:event__okButActionPerformed

    private void _closeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__closeButActionPerformed
        _dialogResult = 0;
        dispose();
    }//GEN-LAST:event__closeButActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> _booltloaderList;
    private javax.swing.JButton _closeBut;
    private javax.swing.JButton _customBootloaderBrowseBut;
    private javax.swing.JTextField _customBootloaderTxt;
    private javax.swing.JButton _okBut;
    private BootloaderSelectionModel bootloaderSelectionModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
